version: '3.4'

services:
  external_paymentgateway:
    image: externalpaymentgateway:${BRANCH_NAME}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

  message_broker:
    ports:
      - "15672"


  mongo:
    ports:
      - "27017"
    
