version: '3.4'

services:
  external.paymentgateway:
    image: externalpaymentgateway:${BRANCH_NAME}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

  mongo:
    ports:
      - "27017"
    
